from __future__ import annotations

import argparse

import yaml
from repo_paths import REPO_ROOT

OUTPUT = REPO_ROOT / "STATUS.md"


def render() -> str:
    phase_status = yaml.safe_load((REPO_ROOT / "phase_status.yml").read_text(encoding="utf-8"))
    current_task = yaml.safe_load((REPO_ROOT / "CURRENT_TASK.yml").read_text(encoding="utf-8"))
    completed = [p for p in phase_status["phases"] if p["status"] == "completed"]
    active = current_task["active_phase"]
    lines = [
        "# Status",
        "",
        f"Project: `{phase_status['project']}`",
        f"Current task: `{current_task['task_id']}`",
        f"Active phase: `{active}`",
        f"Completed phases: `{len(completed)}`",
        "",
        "## Phase Snapshot",
        "",
        "| Phase | Status | Contract | Audit |",
        "| --- | --- | --- | --- |",
    ]
    for phase in phase_status["phases"]:
        lines.append(
            f"| {phase['phase_id']} | {phase['status']} | `{phase['contract']}` | "
            f"`{phase['audit_packet']}` |"
        )
    lines.extend(
        [
            "",
            "## Verification",
            "",
            "Latest results are written to `reports/active/verify_results.json` and "
            "`reports/active/latest_verify.txt`.",
            "",
            "This file is generated by `scripts/generate_status.py`.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale")
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
