from __future__ import annotations

import sys

from repo_paths import REPO_ROOT

sys.path.insert(0, str(REPO_ROOT / "src"))

from poker_training_bot.poker_core.cards import card_texts
from poker_training_bot.poker_core.golden import replay_golden_hands

FIXTURE = REPO_ROOT / "data" / "samples" / "phase_01_golden_hands.json"
OUTPUT = REPO_ROOT / "reports" / "active" / "latest_replay_report.txt"


def render_report() -> str:
    results = replay_golden_hands(FIXTURE)
    lines = [
        "Phase 01 Replay Report",
        "======================",
        "",
        f"Fixture: `{FIXTURE.relative_to(REPO_ROOT)}`",
        f"Hands replayed: {len(results)}",
        "",
    ]
    for hand, settlement in results:
        lines.extend(
            [
                f"## {hand.hand_id}",
                "",
                hand.description,
                "",
                f"Board: {' '.join(card_texts(hand.board))}",
                f"Total pot: {settlement.total_pot}",
                "",
                "Players:",
            ]
        )
        for player in hand.players:
            rank = settlement.showdown_ranks.get(player.seat)
            rank_text = rank.describe() if rank is not None else "folded before showdown"
            lines.append(
                (
                    "- seat {seat} {name}: hole {hole}, committed {committed}, "
                    "payout {payout}, {rank}"
                ).format(
                    seat=player.seat,
                    name=player.name,
                    hole=" ".join(card_texts(player.hole_cards)),
                    committed=player.committed_total,
                    payout=settlement.payouts[player.seat],
                    rank=rank_text,
                )
            )
        lines.extend(["", "Pots:"])
        for index, pot in enumerate(settlement.pots, start=1):
            lines.append(
                (
                    "- pot {index}: amount {amount}, eligible {eligible}, "
                    "winners {winners}, {rank}"
                ).format(
                    index=index,
                    amount=pot.amount,
                    eligible=", ".join(str(seat) for seat in pot.eligible_seats),
                    winners=", ".join(str(seat) for seat in pot.winner_seats),
                    rank=pot.hand_rank.describe(),
                )
            )
        lines.append("")
    lines.append("Generated by `scripts/generate_phase_01_replay_report.py`.")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render_report(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
