from __future__ import annotations

import argparse

import yaml
from repo_paths import REPO_ROOT

OUTPUT = REPO_ROOT / "docs" / "BACKLOG.md"


def render() -> str:
    backlog = yaml.safe_load((REPO_ROOT / "backlog.yml").read_text(encoding="utf-8"))
    lines = [
        "# Backlog",
        "",
        "| ID | Status | Phase | Title | Reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in backlog["items"]:
        lines.append(
            f"| {item['id']} | {item['status']} | {item['phase']} | "
            f"{item['title']} | {item['reason']} |"
        )
    lines.extend(["", "Generated by `scripts/generate_backlog.py`."])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale")
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
