from __future__ import annotations

import sys

from repo_paths import REPO_ROOT

sys.path.insert(0, str(REPO_ROOT / "src"))

from poker_training_bot.hand_history import load_hand_history_file
from poker_training_bot.hand_history.replay import DecisionPoint, replay_hand
from poker_training_bot.poker_core.cards import card_texts
from poker_training_bot.strategy.contract import (
    DECISION_AUDIT_SCHEMA_VERSION,
    DecisionAuditRecord,
    StrategyDecision,
    StrategyQuery,
    records_to_jsonl,
)
from poker_training_bot.strategy.reference import CheckFoldStrategy

FIXTURE = REPO_ROOT / "data" / "samples" / "normalized_hands.json"
AUDIT_OUTPUT = REPO_ROOT / "reports" / "active" / "latest_decision_audit.jsonl"
REPORT_OUTPUT = REPO_ROOT / "reports" / "active" / "latest_strategy_query_report.txt"


def build_query(point: DecisionPoint, hole_cards: tuple[str, str]) -> StrategyQuery:
    state = point.turn.round
    player = state.player(point.seat)
    return StrategyQuery(
        hand_id=point.hand.hand_id,
        street=point.street.value,
        seat=point.seat,
        button_seat=point.hand.button_seat,
        hole_cards=hole_cards,
        board=tuple(card_texts(point.board)),
        legal_actions=tuple(kind.value for kind in point.legal_actions),
        to_call=min(max(0, state.current_bet - player.street_bet), player.stack),
        street_bet=player.street_bet,
        min_raise_target=state.current_bet + state.min_raise,
        pot=point.pot,
        stacks=tuple(
            (seat_player.seat, seat_player.stack)
            for seat_player in sorted(state.players, key=lambda entry: entry.seat)
        ),
        blinds=(point.hand.blinds.small_blind, point.hand.blinds.big_blind),
    )


def render_reports() -> tuple[str, str]:
    strategy = CheckFoldStrategy()
    records: list[DecisionAuditRecord] = []
    lines = [
        "Strategy Query Report",
        "=====================",
        "",
        f"Fixture: `{FIXTURE.relative_to(REPO_ROOT)}`",
        f"Strategy: {strategy.strategy_id} v{strategy.strategy_version}",
        "",
    ]
    totals = {"points": 0, "queried": 0, "skipped": 0, "refusals": 0, "agreements": 0}
    for hand in load_hand_history_file(FIXTURE):
        points: list[DecisionPoint] = []
        replay_hand(hand, on_decision=points.append)
        hole_cards = {
            entry.seat: tuple(card_texts(entry.hole_cards)) for entry in hand.showdown
        }
        queried = skipped = refusals = agreements = 0
        for point in points:
            if point.seat not in hole_cards:
                skipped += 1
                continue
            query = build_query(point, hole_cards[point.seat])
            outcome = strategy.decide(query)
            records.append(
                DecisionAuditRecord(
                    schema_version=DECISION_AUDIT_SCHEMA_VERSION,
                    strategy_id=strategy.strategy_id,
                    strategy_version=strategy.strategy_version,
                    query=query,
                    outcome=outcome,
                )
            )
            queried += 1
            if isinstance(outcome, StrategyDecision):
                if outcome.action == point.action.kind.value:
                    agreements += 1
            else:
                refusals += 1
        totals["points"] += len(points)
        totals["queried"] += queried
        totals["skipped"] += skipped
        totals["refusals"] += refusals
        totals["agreements"] += agreements
        lines.extend(
            [
                f"## {hand.hand_id}",
                "",
                f"Decision points: {len(points)}",
                f"Queried: {queried}",
                f"Skipped (no recorded hole cards): {skipped}",
                f"Refusals: {refusals}",
                f"Reference strategy agreed with the recorded action: {agreements}",
                "",
            ]
        )
    lines.extend(
        [
            "## Totals",
            "",
            f"Decision points: {totals['points']}",
            f"Queried: {totals['queried']}",
            f"Skipped (no recorded hole cards): {totals['skipped']}",
            f"Refusals: {totals['refusals']}",
            f"Agreements: {totals['agreements']}",
            f"Audit records written: {len(records)}",
            "",
            "Generated by `scripts/generate_strategy_query_report.py`.",
        ]
    )
    return "\n".join(lines) + "\n", records_to_jsonl(records)


def main() -> int:
    report_text, audit_jsonl = render_reports()
    REPORT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    REPORT_OUTPUT.write_text(report_text, encoding="utf-8")
    AUDIT_OUTPUT.write_text(audit_jsonl, encoding="utf-8")
    print(f"wrote {REPORT_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"wrote {AUDIT_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
