from __future__ import annotations

import sys

from repo_paths import REPO_ROOT

sys.path.insert(0, str(REPO_ROOT / "src"))

from poker_training_bot.hand_history import load_hand_history_file, replay_hands
from poker_training_bot.poker_core.cards import card_texts

FIXTURE = REPO_ROOT / "data" / "samples" / "normalized_hands.json"
OUTPUT = REPO_ROOT / "reports" / "active" / "latest_hand_history_replay_report.txt"


def render_report() -> str:
    replays = replay_hands(load_hand_history_file(FIXTURE))
    lines = [
        "Hand-History Replay Report",
        "==========================",
        "",
        f"Fixture: `{FIXTURE.relative_to(REPO_ROOT)}`",
        f"Hands replayed: {len(replays)}",
        "",
    ]
    for replay in replays:
        hand = replay.hand
        lines.extend(
            [
                f"## {hand.hand_id}",
                "",
                f"Table: {hand.table_id} ({hand.max_seats} max)",
                f"Button seat: {hand.button_seat}",
                f"Board: {' '.join(card_texts(hand.board))}",
                f"Total pot: {replay.settlement.total_pot}",
                f"Expected result matched: {replay.passed_expected_result}",
                "",
                "Committed chips:",
            ]
        )
        for seat, amount in sorted(replay.committed_by_seat.items()):
            lines.append(f"- seat {seat}: {amount}")
        lines.extend(["", "Payouts:"])
        for seat, amount in sorted(replay.settlement.payouts.items()):
            lines.append(f"- seat {seat}: {amount}")
        lines.extend(["", "Pots:"])
        for index, pot in enumerate(replay.settlement.pots, start=1):
            lines.append(
                (
                    "- pot {index}: amount {amount}, eligible {eligible}, "
                    "winners {winners}, {rank}"
                ).format(
                    index=index,
                    amount=pot.amount,
                    eligible=", ".join(str(seat) for seat in pot.eligible_seats),
                    winners=", ".join(str(seat) for seat in pot.winner_seats),
                    rank=pot.hand_rank.describe() if pot.hand_rank else "uncontested",
                )
            )
        lines.append("")
    lines.append("Generated by `scripts/generate_hand_history_replay_report.py`.")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render_report(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
