"""Report what the committed preflop chart artifacts cover, and what they refuse.

The coverage table lets a non-coding reviewer check which spots exist, and the
probe table shows the fail-closed path: an uncovered table size, stack depth,
position, spot, or hand class returns an explicit miss code, never a guess.
"""

from __future__ import annotations

import sys

try:
    from repo_paths import REPO_ROOT
except ModuleNotFoundError:
    from scripts.repo_paths import REPO_ROOT

sys.path.insert(0, str(REPO_ROOT / "src"))

from poker_training_bot.solver_artifacts.importer import (
    ArtifactImportError,
    import_preflop_artifacts,
)
from poker_training_bot.solver_artifacts.lookup import (
    ChartHit,
    ChartQuery,
    PreflopChartLibrary,
)
from poker_training_bot.solver_artifacts.schema import PreflopAction

ARTIFACT_DIR = REPO_ROOT / "data" / "artifacts" / "preflop"
REPORT_OUTPUT = REPO_ROOT / "reports" / "active" / "latest_preflop_chart_report.txt"

PROBES = [
    (
        "covered: cutoff open with aces",
        ChartQuery(6, 100, "CO", (), "AA"),
    ),
    (
        "covered: cutoff open with seven-deuce offsuit",
        ChartQuery(6, 100, "CO", (), "72o"),
    ),
    (
        "covered: big blind defending a cutoff open with ace-king suited",
        ChartQuery(6, 100, "BB", (PreflopAction("CO", "raise"),), "AKs"),
    ),
    (
        "uncovered table size",
        ChartQuery(9, 100, "CO", (), "AA"),
    ),
    (
        "uncovered stack depth",
        ChartQuery(6, 40, "CO", (), "AA"),
    ),
    (
        "position that does not exist at a six-handed table",
        ChartQuery(6, 100, "UTG", (), "AA"),
    ),
    (
        "uncovered spot: cutoff facing a lojack open",
        ChartQuery(6, 100, "CO", (PreflopAction("LJ", "raise"),), "AA"),
    ),
    (
        "spot v1 cannot represent: big blind facing a four-bet",
        ChartQuery(
            6,
            100,
            "BB",
            (
                PreflopAction("CO", "raise"),
                PreflopAction("BB", "raise"),
                PreflopAction("CO", "raise"),
            ),
            "AA",
        ),
    ),
]


def describe_weights(weights: tuple[tuple[str, float], ...]) -> str:
    return ", ".join(f"{action} {weight}" for action, weight in weights)


def render_report() -> str:
    artifacts = import_preflop_artifacts(ARTIFACT_DIR)
    library = PreflopChartLibrary.from_artifacts(artifacts)
    lines = [
        "Preflop Chart Report",
        "====================",
        "",
        f"Artifact directory: `{ARTIFACT_DIR.relative_to(REPO_ROOT)}`",
        f"Artifacts imported: {len(artifacts)}",
        "",
    ]
    for artifact in artifacts:
        positions = sorted({spot.hero_position for spot in artifact.spots})
        lines.extend(
            [
                f"## {artifact.artifact_id}",
                "",
                f"Source: {artifact.source.name}",
                f"Source kind: {artifact.source.kind}",
                f"Source reference: {artifact.source.reference}",
                f"Generated at: {artifact.generated_at}",
                f"Table size: {artifact.table_size}",
                f"Stack depth: {artifact.stack_depth_bb} bb",
                "Import: accepted",
                f"Weights checksum (recomputed and matched at import):"
                f" {artifact.audit_fields.weights_sha256}",
                f"Spots: {artifact.audit_fields.spot_count}",
                f"Hero positions covered: {', '.join(positions)}",
                f"Distinct hand classes covered: {artifact.audit_fields.hand_class_count} of 169",
                "",
                "Spot keys:",
            ]
        )
        lines.extend(f"- `{spot.spot_id}`" for spot in artifact.spots)
        lines.append("")
    lines.extend(["## Lookup probes", ""])
    for label, query in PROBES:
        result = library.lookup(query)
        if isinstance(result, ChartHit):
            verdict = f"hit -> {describe_weights(result.action_weights)}"
        else:
            verdict = f"miss -> {result.code}"
        lines.append(f"- {label}: {verdict}")
    lines.extend(
        [
            "",
            "A miss is the correct answer for an uncovered spot. Phase 04 never fills a gap",
            "with a default action, a nearest spot, or a nearest stack depth.",
            "",
            "Generated by `scripts/generate_preflop_chart_report.py`.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_rejection(error: ArtifactImportError) -> str:
    """A rejected directory still produces a report, so the failure is visible."""
    return "\n".join(
        [
            "Preflop Chart Report",
            "====================",
            "",
            f"Artifact directory: `{ARTIFACT_DIR.relative_to(REPO_ROOT)}`",
            "Artifacts imported: 0",
            "",
            "## Import rejected",
            "",
            f"Reason code: {error.code}",
            f"Detail: {error.message}",
            "",
            "Import is all-or-nothing. No chart is usable until this is fixed.",
            "",
            "Generated by `scripts/generate_preflop_chart_report.py`.",
        ]
    ) + "\n"


def main() -> int:
    REPORT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    try:
        report_text = render_report()
    except ArtifactImportError as error:
        REPORT_OUTPUT.write_text(render_rejection(error), encoding="utf-8")
        print(f"artifact import rejected: {error}", file=sys.stderr)
        return 1
    REPORT_OUTPUT.write_text(report_text, encoding="utf-8")
    print(f"wrote {REPORT_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
