from __future__ import annotations

import argparse

import yaml
from repo_paths import REPO_ROOT

OUTPUT = REPO_ROOT / "docs" / "PHASE_LEDGER.md"


def render() -> str:
    phase_status = yaml.safe_load((REPO_ROOT / "phase_status.yml").read_text(encoding="utf-8"))
    lines = [
        "# Phase Ledger",
        "",
        "| Phase | Title | Status | Contract | Audit Packet |",
        "| --- | --- | --- | --- | --- |",
    ]
    for phase in phase_status["phases"]:
        lines.append(
            f"| {phase['phase_id']} | {phase['title']} | {phase['status']} | "
            f"`{phase['contract']}` | `{phase['audit_packet']}` |"
        )
    lines.extend(["", "Generated by `scripts/generate_phase_ledger.py`."])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is stale")
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
