"""Committed raise sizes, taken from the solution the ranges came from.

A spot key carries no raise size, so the artifact cannot hold one, and a strategy
still has to raise some amount. That gap is where invented numbers get in: a model
asked to pick an open size will happily pick a plausible one, and it then becomes
the bot's entire preflop sizing strategy without anyone deciding it.

So sizes live here as data with their own provenance, generated by
`scripts/convert_preflop_export.py` from the same export as the ranges. A spot with
no entry has no size, and the strategy refuses rather than guessing.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

SCHEMA_VERSION = 1
DEFAULT_PATH = (
    Path(__file__).resolve().parents[3]
    / "data"
    / "artifacts"
    / "preflop"
    / "sizings"
    / "six_max_nl25_100bb.json"
)


@dataclass(frozen=True)
class PreflopSizingTable:
    """Raise-to amounts in big blinds, keyed by the same spot keys as the charts."""

    source_name: str
    source_kind: str
    raise_to_bb: Mapping[str, float]

    @classmethod
    def from_json(cls, path: Path | str) -> PreflopSizingTable:
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if payload.get("schema_version") != SCHEMA_VERSION:
            raise ValueError(
                f"{path}: sizing schema_version {payload.get('schema_version')!r}"
                f" is not {SCHEMA_VERSION}"
            )
        source = payload["source"]
        sizes = payload["raise_to_bb"]
        for spot_key_text, amount in sizes.items():
            if not isinstance(amount, int | float) or amount <= 0:
                raise ValueError(f"{path}: {spot_key_text} has a non-positive size {amount!r}")
        return cls(
            source_name=source["name"],
            source_kind=source["kind"],
            raise_to_bb=dict(sizes),
        )

    @classmethod
    def from_repo(cls) -> PreflopSizingTable:
        return cls.from_json(DEFAULT_PATH)

    def amount_bb(self, spot_key_text: str) -> float | None:
        """The raise-to size for a spot, or None when the table does not cover it.

        None is the useful answer, not an error: an uncovered spot is a refusal
        upstream, and raising a default here would be the guess this exists to stop.
        """
        return self.raise_to_bb.get(spot_key_text)
