"""Committed raise sizes, taken from the solution the ranges came from.

A spot key carries no raise size, so the artifact cannot hold one, and a strategy
still has to raise some amount. That gap is where invented numbers get in: a model
asked to pick an open size will happily pick a plausible one, and it then becomes
the bot's entire preflop sizing strategy without anyone deciding it.

So sizes live here as data with their own provenance, generated by
`scripts/convert_preflop_export.py` from the same export as the ranges. A spot with
no entry has no size, and the strategy refuses rather than guessing.

Schema 2, decision 6 as re-cut by Taylor on 2026-08-26: **the prices are per hand class.**
Version 1 held one float per spot, which cannot describe the solve at all. On the export
that ruling was taken against, `t6/d100/BB/BTN:raise@2.5` priced 18 classes at two sizes
each and the rest at one, so a single number per spot either priced the 95 classes that only
fold or call there - inventing a raise the chart does not offer - or dropped aces, which
raise at one price and never jam. An entry is therefore a list of `{"to_bb", "weight"}` pairs
in ascending price order, one list per class, and the weights are hero's own frequencies on
those prices. Which price the bot picks between two is not answered here and is not answered
by this phase: `sizes_bb` hands both back with their weights and lets the strategy own the
draw.

The chart the cutover commits happens to name one price at every class it prices, so every
list in the current file is a single pair. The list stays because the shape is a ruling about
what a spot may say, not a count of what today's file says, and the multiway family that
returns once GTOpen can price it brings two-price menus back with it.
"""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

SCHEMA_VERSION = 2
WEIGHT_SUM_TOLERANCE = 1e-6
_ENTRY_KEYS = {"to_bb", "weight"}
DEFAULT_PATH = (
    Path(__file__).resolve().parents[3]
    / "data"
    / "artifacts"
    / "preflop"
    / "sizings"
    / "six_max_100bb_rakefree.json"
)

# Spot key -> hand class -> the prices that class raises to, each with hero's weight on it.
# Held in the payload's own shape rather than converted on load, so a reader comparing the
# table against the file it came from is comparing like with like.
PriceEntries = Sequence[Mapping[str, float]]
RaiseToBb = Mapping[str, Mapping[str, PriceEntries]]


def _validate_entries(
    origin: str, spot_key_text: str, hand_class_text: str, entries: object
) -> None:
    """A class's price list, checked hard enough that a reader can trust the indexing."""
    context = f"{origin}: {spot_key_text}[{hand_class_text}]"
    if not isinstance(entries, list) or not entries:
        raise ValueError(f"{context} must hold at least one price entry, got {entries!r}")
    prices: list[float] = []
    total = 0.0
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != _ENTRY_KEYS:
            raise ValueError(
                f"{context} entries must hold exactly {sorted(_ENTRY_KEYS)}, got {entry!r}"
            )
        for name in sorted(_ENTRY_KEYS):
            value = entry[name]
            if isinstance(value, bool) or not isinstance(value, int | float):
                raise ValueError(f"{context}.{name} must be a number, got {value!r}")
            if value <= 0:
                raise ValueError(f"{context}.{name} must be positive, got {value!r}")
        prices.append(float(entry["to_bb"]))
        total += float(entry["weight"])
    if prices != sorted(prices) or len(set(prices)) != len(prices):
        raise ValueError(f"{context} prices must ascend without repeating, got {prices}")
    if abs(total - 1.0) > WEIGHT_SUM_TOLERANCE:
        raise ValueError(
            f"{context} weights sum to {total!r}, outside {WEIGHT_SUM_TOLERANCE!r} of 1.0;"
            " they are hero's frequencies on the prices offered and describe one range"
        )


@dataclass(frozen=True)
class PreflopSizingTable:
    """Raise-to amounts in big blinds, keyed by the same spot keys as the charts.

    `source_kind` is recorded rather than checked against a vocabulary: a fixture is a
    legitimate source for a table built in a test, and the artifact schema is where the
    provenance of committed ranges is policed.
    """

    source_name: str
    source_kind: str
    raise_to_bb: RaiseToBb

    @classmethod
    def from_json(cls, path: Path | str) -> PreflopSizingTable:
        """Load a table, keeping apart two things a reader must not confuse.

        A spot **absent** from the table is one whose menu offers hero no raise at all. There
        is nothing to price there, and the strategy refuses when asked for a size rather than
        inventing one.

        A spot **present with an empty class map** is a different fact: the menu does offer
        hero a raise, and no hand he can be holding when he arrives there ever takes it. As
        the chart stands after the cutover that is 81 of its 249 spots, every one of them
        facing a three-bet - hero opened or flatted, someone raised, and against that raise
        his whole arriving range folds or calls. The solve says so, and an empty map is how
        the artifact says it, so this loader records it rather than rejecting it. The old rule
        refusing an empty map was only ever safe because the retired 86-spot chart happened to
        price something everywhere.

        Nothing else relaxes. A spot must still be a map, and a class that is present must
        still carry at least one real price, because a class listed with nothing under it is a
        hand the chart claims to raise and cannot say how much with. The refusal a reader
        wants at an empty spot comes from `sizes_bb` answering None for every class there, not
        from failing to load the file at all.
        """
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        if payload.get("schema_version") != SCHEMA_VERSION:
            raise ValueError(
                f"{path}: sizing schema_version {payload.get('schema_version')!r}"
                f" is not {SCHEMA_VERSION}"
            )
        source = payload["source"]
        sizes = payload["raise_to_bb"]
        for spot_key_text, classes in sizes.items():
            # Empty is allowed and meaningful; see `from_json`'s docstring. Not a dict is not.
            if not isinstance(classes, dict):
                raise ValueError(
                    f"{path}: {spot_key_text} must hold a map of hand classes, got {classes!r}"
                )
            for hand_class_text, entries in classes.items():
                _validate_entries(str(path), spot_key_text, hand_class_text, entries)
        return cls(
            source_name=source["name"],
            source_kind=source["kind"],
            raise_to_bb={
                spot_key_text: {
                    hand_class_text: [dict(entry) for entry in entries]
                    for hand_class_text, entries in classes.items()
                }
                for spot_key_text, classes in sizes.items()
            },
        )

    @classmethod
    def from_repo(cls) -> PreflopSizingTable:
        return cls.from_json(DEFAULT_PATH)

    def sizes_bb(
        self, spot_key_text: str, hand_class_text: str
    ) -> tuple[tuple[float, float], ...] | None:
        """One class's prices at one spot, each with hero's weight, or None if uncovered.

        None rather than an empty tuple, and the difference carries meaning at both levels.
        A spot the table does not hold is one whose menu offers hero no raise at all, so it
        has nothing to price; a spot the table holds with no classes under it offers a raise
        that no arriving hand takes. Those are different facts about the solve, and the
        artifact keeps them apart, but both answer None here for every class - which is what
        makes the strategy refuse rather than invent a size at either. Inside a spot that does
        price something, the classes carrying entries are exactly the classes the chart raises
        with, so a class answering None there is a hand hero only folds or flats.

        The order is the table's own, which `from_json` requires to be ascending by price. It
        is not sorted here on purpose: a reader that sorted could not tell an unordered table
        from an ordered one, which is the property the loader exists to establish.
        """
        entries = self.raise_to_bb.get(spot_key_text, {}).get(hand_class_text)
        if entries is None:
            return None
        return tuple((float(entry["to_bb"]), float(entry["weight"])) for entry in entries)

    def amount_bb(self, spot_key_text: str, hand_class_text: str) -> float | None:
        """The one price a class raises to at a spot, or None when there is not exactly one.

        None is the useful answer, not an error: an uncovered spot is a refusal upstream, and
        raising a default here would be the guess this file exists to stop. Two prices are
        None for the same reason - picking between them is a strategy decision, and this
        layer choosing the larger, the smaller, or the likelier would be that decision made
        by whoever wrote the accessor.
        """
        entries = self.sizes_bb(spot_key_text, hand_class_text)
        if entries is None or len(entries) != 1:
            return None
        return entries[0][0]
