name: verify

on:
  pull_request:
  push:

jobs:
  verify:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Verify
        shell: bash
        run: scripts/verify.sh
